"use client";
import { useState } from "react";

const stages=["Idea","Research","Script","SEO","Visual Plan","Repurpose","Publish","Analytics"];

export default function YouTubeAutoPage(){
 const [topic,setTopic]=useState(""); const [stage,setStage]=useState("Idea"); const [output,setOutput]=useState(""); const [loading,setLoading]=useState(false);
 async function run(){ if(!topic.trim()||loading)return; setLoading(true); setOutput(""); try{const r=await fetch("/api/agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:`YouTube Automation Studio task. Stage: ${stage}. Topic/channel goal: ${topic}. Create a practical, original, reviewable output for this stage. If stage is Idea give strong video concepts; Research give research angles and facts to verify; Script give a retention-focused script outline/draft; SEO give title, description and tags; Visual Plan give thumbnail and scene plan; Repurpose give Shorts/Reels ideas; Publish give an upload checklist; Analytics give metrics to watch and next experiments.`})}); const d=await r.json(); setOutput(r.ok?(d.output||"No output returned."):(d.error||"Could not complete the task."));}catch{setOutput("Connection problem. Please try again.")}finally{setLoading(false)}}
 return <main style={{minHeight:"100vh",padding:"28px",background:"#070b14",color:"white"}}><div style={{maxWidth:1100,margin:"0 auto"}}><button onClick={()=>history.back()} style={{marginBottom:18}}>← Dashboard</button><div style={{letterSpacing:2,fontSize:12,opacity:.7}}>CREATORFLOW AI · YOUTUBE AUTOMATION</div><h1 style={{fontSize:36,margin:"8px 0"}}>YouTube Auto Studio</h1><p style={{opacity:.75,maxWidth:760}}>Build a complete YouTube workflow from one workspace: idea → research → script → SEO → visual plan → Shorts → publishing checklist → analytics.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"24px 0"}}>{stages.map(x=><button key={x} onClick={()=>setStage(x)} style={{padding:"10px 14px",borderRadius:10,border:"1px solid #263247",background:stage===x?"#18243a":"transparent",color:"white"}}>{x}</button>)}</div><div style={{border:"1px solid #263247",borderRadius:16,padding:18,background:"#0c1220"}}><label style={{display:"block",fontWeight:600,marginBottom:8}}>{stage} brief</label><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Example: Start a faceless YouTube channel about beginner technology tips for a USA audience…" style={{width:"100%",minHeight:130,borderRadius:12,padding:14,background:"#070b14",color:"white",border:"1px solid #263247"}}/><button onClick={run} disabled={!topic.trim()||loading} style={{marginTop:12,padding:"12px 18px",borderRadius:10}}>{loading?"Working…":`Run ${stage}`}</button></div>{output&&<div style={{marginTop:18,border:"1px solid #263247",borderRadius:16,padding:18,background:"#0c1220"}}><h2>Output</h2><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",lineHeight:1.6}}>{output}</pre></div>}<p style={{fontSize:12,opacity:.55,marginTop:18}}>Publishing and account connections remain user-controlled and require explicit authorization.</p></div></main>
}
