"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Item={id:string;title:string;type:string;content:string;created_at:string};
export default function Saved(){
 const [items,setItems]=useState<Item[]>([]); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true); const [action,setAction]=useState(""); const router=useRouter();
 useEffect(()=>{fetch("/api/saved",{cache:"no-store"}).then(r=>r.json()).then(d=>setItems(Array.isArray(d.items)?d.items:[])).catch(()=>setItems([])).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>items.filter(x=>(x.title+" "+x.type+" "+x.content).toLowerCase().includes(q.toLowerCase())),[items,q]);
 function flash(message:string){setAction(message);setTimeout(()=>setAction(""),1600)}
 async function copy(text:string){try{await navigator.clipboard?.writeText(text);flash("Copied ✓")}catch{flash("Copy failed")}}
 async function del(id:string){if(!confirm("Delete this saved item?"))return;try{const r=await fetch("/api/delete",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,table:"saved_content"})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not delete");setItems(x=>x.filter(i=>i.id!==id));flash("Deleted ✓")}catch(e){flash(e instanceof Error?e.message:"Delete failed")}}
 return <main style={{maxWidth:1100,margin:"0 auto",padding:"24px 16px 60px"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:16,marginBottom:24,flexWrap:"wrap"}}><div><div style={{fontWeight:900,fontSize:22}}>Creator<span style={{color:"#8b7cff"}}>Flow</span> AI</div><div className="cf-muted" style={{marginTop:6,fontSize:13}}>Your saved content library</div><h1 style={{margin:"10px 0 0",fontSize:"clamp(28px,5vw,38px)"}}>Saved Content</h1></div><div style={{display:"flex",gap:9,alignItems:"center"}}>{action&&<span className="cf-muted" style={{fontSize:13}}>{action}</span>}<button className="cf-btn" onClick={()=>router.push("/dashboard")}>← Dashboard</button></div></header><section className="cf-card cf-glow" style={{padding:18,marginBottom:18}}><b>Your library</b><div className="cf-muted" style={{fontSize:12,margin:"4px 0 10px"}}>{filtered.length} saved item{filtered.length===1?"":"s"}</div><input className="cf-input" aria-label="Search saved content" placeholder="Search saved content..." value={q} onChange={e=>setQ(e.target.value)}/></section>{loading?<div className="cf-card" style={{padding:28,textAlign:"center"}}>Loading saved content…</div>:filtered.length===0?<div className="cf-card" style={{padding:42,textAlign:"center"}}><div style={{fontSize:34}}>☆</div><h2>No saved content yet</h2><p className="cf-muted">{q?"Try a different search term.":"Save useful AI outputs and they will appear here."}</p><button className="cf-btn" onClick={()=>router.push("/dashboard")}>Create something →</button></div>:<div style={{display:"grid",gap:14}}>{filtered.map(i=><article className="cf-card" style={{padding:18}} key={i.id}><div style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div style={{minWidth:0,flex:1}}><b>{i.title||"Untitled"}</b><div className="cf-muted" style={{fontSize:11,marginTop:6}}>{i.type} • {new Date(i.created_at).toLocaleString()}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="cf-btn" onClick={()=>copy(i.content)}>Copy</button><button className="cf-btn" onClick={()=>del(i.id)}>Delete</button></div></div><div style={{marginTop:15,padding:15,borderRadius:15,background:"rgba(255,255,255,.035)",border:"1px solid rgba(255,255,255,.07)"}}><pre style={{margin:0,whiteSpace:"pre-wrap",fontFamily:"inherit",lineHeight:1.65,overflowWrap:"anywhere",fontSize:14}}>{i.content}</pre></div></article>)}</div>}</main>;
}
