"use client";
import {useMemo,useState} from "react";

type Row={day:number,platform:string,type:string,topic:string,hook:string,cta:string};
const platforms=["YouTube","Instagram","TikTok","Facebook","LinkedIn","X","Threads","Pinterest","Email","Blog & SEO"];
const types=["Long video","Short video","Post","Carousel","Thread","Newsletter","Article"];
export default function ContentCalendar(){
 const [days,setDays]=useState("7"),[topic,setTopic]=useState("AI creator tips"),[goal,setGoal]=useState("Grow audience"),[start,setStart]=useState(()=>new Date().toISOString().slice(0,10));
 const rows=useMemo<Row[]>(()=>{const n=Math.min(30,Math.max(1,Number(days)||7));return Array.from({length:n},(_,i)=>{const p=platforms[i%platforms.length];const type=types[i%types.length];return {day:i+1,platform:p,type,topic:`${topic.trim()||"Content idea"} — ${goal}`,hook:["Stop scrolling—try this simple approach.","3 mistakes creators should avoid.","Here is the practical step-by-step.","If I started today, I would do this first."][i%4],cta:["Save this for later.","Comment with your biggest challenge.","Follow for the next practical tip.","Share with a creator who needs this."][i%4]}})},[days,topic,goal]);
 return <section className="cf-card" style={{padding:18}}><div className="cf-eyebrow">PUBLISHING SYSTEM</div><h2>Cross-platform Content Calendar</h2><p className="cf-muted">Build a practical publishing plan. Dates and ideas are planning suggestions—not guaranteed reach.</p><div className="cf-form-grid"><label>Start date<input className="cf-input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Days<input className="cf-input" inputMode="numeric" value={days} onChange={e=>setDays(e.target.value)}/></label><label>Main topic<input className="cf-input" value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>Goal<select className="cf-input" value={goal} onChange={e=>setGoal(e.target.value)}><option>Grow audience</option><option>Increase engagement</option><option>Promote a product</option><option>Build authority</option><option>Drive website traffic</option></select></label></div><div style={{overflowX:"auto",marginTop:18}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Day","Platform","Format","Topic","Hook","CTA"].map(h=><th key={h} style={{textAlign:"left",padding:"10px 8px",borderBottom:"1px solid rgba(255,255,255,.12)"}}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.day}><td style={{padding:"10px 8px"}}>{r.day}</td><td style={{padding:"10px 8px"}}>{r.platform}</td><td style={{padding:"10px 8px"}}>{r.type}</td><td style={{padding:"10px 8px"}}>{r.topic}</td><td style={{padding:"10px 8px"}}>{r.hook}</td><td style={{padding:"10px 8px"}}>{r.cta}</td></tr>)}</tbody></table></div></section>;
}
