"use client";
import {useEffect,useMemo,useState} from "react";

type Row={day:number,date:string,platform:string,type:string,topic:string,hook:string,cta:string};
type SavedPlan={id:string,savedAt:string,start:string,days:string,topic:string,goal:string,rows:Row[]};
const platforms=["YouTube","Instagram","TikTok","Facebook","LinkedIn","X","Threads","Pinterest","Email","Blog & SEO"];
const types=["Long video","Short video","Post","Carousel","Thread","Newsletter","Article"];
const hooks=["Stop scrolling—try this simple approach.","3 mistakes creators should avoid.","Here is the practical step-by-step.","If I started today, I would do this first."];
const ctas=["Save this for later.","Comment with your biggest challenge.","Follow for the next practical tip.","Share with a creator who needs this."];
const STORAGE_KEY="creatorflow:content-calendar-plans";
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const dateFor=(start:string,i:number)=>{const d=new Date(`${start}T12:00:00`);d.setDate(d.getDate()+i);return d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});};
const csvCell=(value:string|number)=>`"${String(value).replace(/"/g,'""')}"`;
export default function ContentCalendar(){
 const [days,setDays]=useState("7"),[topic,setTopic]=useState("AI creator tips"),[goal,setGoal]=useState("Grow audience"),[start,setStart]=useState(localDate);
 const [copied,setCopied]=useState(false),[saved,setSaved]=useState(false),[downloaded,setDownloaded]=useState(false),[savedPlans,setSavedPlans]=useState<SavedPlan[]>([]),[hydrated,setHydrated]=useState(false);
 const rows=useMemo<Row[]>(()=>{const n=Math.min(30,Math.max(1,Number(days)||7));return Array.from({length:n},(_,i)=>{const p=platforms[i%platforms.length];const type=types[i%types.length];return {day:i+1,date:dateFor(start,i),platform:p,type,topic:`${topic.trim()||"Content idea"} — ${goal}`,hook:hooks[i%hooks.length],cta:ctas[i%ctas.length]}})},[days,topic,goal,start]);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed))setSavedPlans(parsed.filter(p=>p&&typeof p.id==="string"&&Array.isArray(p.rows)).slice(0,10));}}catch{}finally{setHydrated(true)}},[]);
 useEffect(()=>{if(hydrated)try{localStorage.setItem(STORAGE_KEY,JSON.stringify(savedPlans))}catch{}},[savedPlans,hydrated]);
 const copy=async()=>{const text=rows.map(r=>`${r.date} | ${r.platform} | ${r.type}\n${r.topic}\nHook: ${r.hook}\nCTA: ${r.cta}`).join("\n\n");try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}};
 const downloadCsv=()=>{const header=["Day","Date","Platform","Format","Topic","Hook","CTA"];const body=rows.map(r=>[r.day,r.date,r.platform,r.type,r.topic,r.hook,r.cta].map(csvCell).join(","));const blob=new Blob([[header.map(csvCell).join(","),...body].join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`creatorflow-content-calendar-${start}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setDownloaded(true);setTimeout(()=>setDownloaded(false),1800)};
 const savePlan=()=>{const plan:SavedPlan={id:crypto.randomUUID(),savedAt:new Date().toISOString(),start,days,topic,goal,rows};setSavedPlans(prev=>[plan,...prev].slice(0,10));setSaved(true);setTimeout(()=>setSaved(false),1800)};
 const loadPlan=(plan:SavedPlan)=>{setStart(plan.start);setDays(plan.days);setTopic(plan.topic);setGoal(plan.goal)};
 const deletePlan=(id:string)=>setSavedPlans(prev=>prev.filter(p=>p.id!==id));
 return <section className="cf-card" style={{padding:18}}><div className="cf-eyebrow">PUBLISHING SYSTEM</div><h2>Cross-platform Content Calendar</h2><p className="cf-muted">Build a practical publishing plan. Dates and ideas are planning suggestions—not guaranteed reach.</p><div className="cf-form-grid"><label>Start date<input className="cf-input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Days<input className="cf-input" inputMode="numeric" min="1" max="30" value={days} onChange={e=>setDays(e.target.value)}/></label><label>Main topic<input className="cf-input" maxLength={120} value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>Goal<select className="cf-input" value={goal} onChange={e=>setGoal(e.target.value)}><option>Grow audience</option><option>Increase engagement</option><option>Promote a product</option><option>Build authority</option><option>Drive website traffic</option></select></label></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:14,flexWrap:"wrap"}}><button className="cf-button" type="button" onClick={savePlan}>{saved?"Saved ✓":"Save plan"}</button><button className="cf-button" type="button" onClick={copy}>{copied?"Copied ✓":"Copy calendar"}</button><button className="cf-button" type="button" onClick={downloadCsv}>{downloaded?"Downloaded ✓":"Download CSV"}</button></div>{savedPlans.length>0&&<div style={{marginTop:16}}><div className="cf-eyebrow">SAVED PLANS</div><div style={{display:"grid",gap:8,marginTop:8}}>{savedPlans.map(plan=><div key={plan.id} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,padding:"10px 12px",border:"1px solid rgba(255,255,255,.1)",borderRadius:10}}><div><strong>{plan.topic||"Content plan"}</strong><div className="cf-muted" style={{fontSize:12}}>{plan.days} days · {plan.goal}</div></div><div style={{display:"flex",gap:6}}><button className="cf-button" type="button" onClick={()=>loadPlan(plan)}>Load</button><button className="cf-button" type="button" onClick={()=>deletePlan(plan.id)}>Delete</button></div></div>)}</div></div>}<div style={{overflowX:"auto",marginTop:10}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Day","Date","Platform","Format","Topic","Hook","CTA"].map(h=><th key={h} style={{textAlign:"left",padding:"10px 8px",borderBottom:"1px solid rgba(255,255,255,.12)"}}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={`${r.day}-${r.date}`}><td style={{padding:"10px 8px"}}>{r.day}</td><td style={{padding:"10px 8px",whiteSpace:"nowrap"}}>{r.date}</td><td style={{padding:"10px 8px"}}>{r.platform}</td><td style={{padding:"10px 8px"}}>{r.type}</td><td style={{padding:"10px 8px",minWidth:190}}>{r.topic}</td><td style={{padding:"10px 8px",minWidth:210}}>{r.hook}</td><td style={{padding:"10px 8px",minWidth:180}}>{r.cta}</td></tr>)}</tbody></table></div></section>;
}
