"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import VisualCreator from "@/components/VisualCreator";
import GrowthTools from "@/components/GrowthTools";
import ContentCalendar from "@/components/ContentCalendar";

const tools=[{id:"youtube",icon:"▶",name:"YouTube Content",desc:"Titles, descriptions, tags & scripts"},{id:"shorts",icon:"⚡",name:"Shorts & Reels",desc:"Hooks and short-form scripts"},{id:"social",icon:"✦",name:"Social Posts",desc:"Facebook, Instagram & TikTok"},{id:"product",icon:"◇",name:"Product Copy",desc:"SEO-ready product descriptions"},{id:"visual",icon:"◈",name:"Visual Creator",desc:"Thumbnails, banners & social art"}];
const languages=["English","বাংলা","Hindi","Spanish","Portuguese","French","German","Arabic","Indonesian","Turkish"];
const tones=["Engaging","Professional","Funny","Inspirational","Direct"];
const starterIdeas=["5 AI tools that can save creators time","A 30-second motivational Reel for beginners","A Facebook post that introduces my new page","SEO product description for a wireless earbud"];
const growthTool=(id:string)=>{const s=id.toLowerCase();return s.includes("watch")||s.includes("subscriber")||s.includes("follower")||s.includes("retention")||s.includes("completion")||s.includes("analyzer")};
const calendarTool=(id:string)=>id.toLowerCase().includes("calendar");
function inferWorkflow(text:string,currentTool:string,currentPlatform:string){
 const s=text.toLowerCase(); let platform=currentPlatform; let tool=currentTool;
 if(/youtube|yt\b/.test(s)) platform="youtube"; else if(/instagram|\big\b|reel/.test(s)) platform="instagram"; else if(/tiktok|tik tok/.test(s)) platform="tiktok"; else if(/facebook|fb\b/.test(s)) platform="facebook"; else if(/linkedin/.test(s)) platform="linkedin"; else if(/shopify|product|ecommerce|e-commerce|store/.test(s)) platform="shopify";
 if(/thumbnail|banner|cover|visual|image|graphic/.test(s)) tool="visual"; else if(/watch.?time|retention|completion|subscriber|follower|analytics|analy[sz]e|growth|views/.test(s)) tool="growth"; else if(/calendar|schedule|content plan/.test(s)) tool="calendar"; else if(/shorts|reel|tiktok video|30.?second|60.?second/.test(s)) tool="shorts"; else if(/product description|product copy|seo product|store copy/.test(s)) tool="product"; else if(/facebook post|instagram post|social post|caption|carousel|linkedin post|thread/.test(s)) tool="social"; else if(/youtube|title|description|tags|long.?form|script/.test(s)) tool="youtube";
 return {tool,platform};
}
type Message={role:"user"|"assistant";text:string};
export default function Dashboard(){
 const[tool,setTool]=useState(tools[0].id),[platform,setPlatform]=useState(""),[language,setLanguage]=useState("English"),[topic,setTopic]=useState(""),[tone,setTone]=useState("Engaging"),[result,setResult]=useState(""),[loading,setLoading]=useState(false),[action,setAction]=useState(""),[credits,setCredits]=useState<number|null>(null),[error,setError]=useState(""),[messages,setMessages]=useState<Message[]>([]);
 const router=useRouter(); const activeTool=useMemo(()=>tools.find(t=>t.id===tool)??{id:tool,icon:"✦",name:tool||"CreatorFlow Tool",desc:`AI workflow for ${platform||"your platform"}`},[tool,platform]);
 useEffect(()=>{loadCredits();const p=new URLSearchParams(window.location.search);const requestedTool=p.get("tool")||"";const requestedPlatform=p.get("platform")||"";if(requestedTool){setTool(requestedTool);setPlatform(requestedPlatform);setTopic(`${requestedTool} for ${requestedPlatform||"my content"}`)}},[]);
 async function loadCredits(){try{const r=await fetch("/api/profile",{cache:"no-store"});const d=await r.json();if(typeof d.credits==="number")setCredits(d.credits)}catch{}}
 async function generate(){const clean=topic.trim();if(!clean||loading)return;const inferred=inferWorkflow(clean,tool,platform);setTool(inferred.tool);setPlatform(inferred.platform);setLoading(true);setResult("");setAction("");setError("");setMessages(prev=>[...prev,{role:"user",text:clean},{role:"assistant",text:"Thinking…"}]);try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tool:inferred.tool,platform:inferred.platform,language,topic:clean,tone})});const data=await r.json();setMessages(prev=>{const copy=[...prev];copy[copy.length-1]={role:"assistant",text:r.ok?(data.output||"No content was returned. Please try again."):(data.error||"We couldn't generate this yet. Please try again.")};return copy});if(!r.ok){setError(data.error||"We couldn't generate this yet. Please try again.");if(typeof data.credits==="number")setCredits(data.credits);return}setResult(data.output||"");if(typeof data.credits==="number")setCredits(data.credits)}catch{const msg="Connection problem. Please try again in a moment";setError(msg);setMessages(prev=>{const copy=[...prev];copy[copy.length-1]={role:"assistant",text:msg};return copy})}finally{setLoading(false)}}
 async function copyResult(){if(!result)return;try{await navigator.clipboard?.writeText(result);setAction("Copied ✓");setTimeout(()=>setAction(""),1600)}catch{setAction("Copy failed")}}
 async function saveResult(){if(!result)return;setAction("Saving...");try{const r=await fetch("/api/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:topic.slice(0,60),type:tool,content:result})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed");setAction("Saved ✓");setTimeout(()=>setAction(""),1600)}catch(e){setAction(e instanceof Error?e.message:"Save failed");setTimeout(()=>setAction(""),2200)}}
 function chooseTool(id:string){setTool(id);setPlatform("");setResult("");setError("");setAction("");setMessages([])} function useIdea(idea:string){setTopic(idea);setError("")}
 const go=(path:"/"|"/history"|"/settings"|"/saved")=>router.push(path); const goVisuals=()=>window.location.assign("/images"); const goPlatforms=()=>window.location.assign("/platforms");
 return <main className="cf-dashboard" style={{maxWidth:1380,margin:"0 auto",padding:"18px 20px 40px"}}><header className="cf-topbar"><button className="cf-brand" onClick={()=>go("/")}><span>Creator</span><strong>Flow</strong><em>AI</em></button><div className="cf-top-actions"><div className="cf-credit"><span>Credits</span><b>{credits??"—"}</b></div><button className="cf-icon-btn" onClick={goPlatforms}>Platform Hub</button><button className="cf-icon-btn" onClick={()=>go("/history")}>History</button><button className="cf-icon-btn" onClick={()=>go("/saved")}>Saved</button><button className="cf-icon-btn" onClick={goVisuals}>Visuals</button><button className="cf-icon-btn" onClick={()=>go("/settings")}>Settings</button></div></header>
 <section className="cf-welcome cf-glow"><div><div className="cf-eyebrow">CREATOR WORKSPACE</div><h1>Your AI creator workspace.</h1><p>Tell CreatorFlow what you want. Pick a tool only when you need more control.</p>{platform&&<div style={{marginTop:14,fontSize:13,opacity:.9}}>Selected workflow: <b>{platform}</b> / <b>{tool}</b></div>}</div><div className="cf-stat"><span>Available credits</span><strong>{credits??"—"}</strong><small>1 credit per successful AI generation</small></div></section>
 <div className="cf-workspace"><aside className="cf-sidebar cf-card"><div className="cf-sidebar-title">TOOLS</div>{tools.map(t=><button key={t.id} className={"cf-tool "+(tool===t.id&&!platform?"active":"")} onClick={()=>chooseTool(t.id)}><span className="cf-tool-icon">{t.icon}</span><span><b>{t.name}</b><small>{t.desc}</small></span><i>›</i></button>)}<button className="cf-tool" onClick={goPlatforms}><span className="cf-tool-icon">▦</span><span><b>Platform Hub</b><small>All platforms, workflows & integrations</small></span><i>›</i></button><div className="cf-sidebar-foot"><span>✦</span><div><b>CreatorFlow AI</b><small>Your all-in-one creator workspace</small></div></div></aside>
 <section className="cf-main">{calendarTool(tool)&&platform?<ContentCalendar/>:growthTool(tool)&&platform?<GrowthTools tool={tool} platform={platform}/>:tool==="visual"&&!platform?<VisualCreator/>:<div className="cf-card cf-generator"><div className="cf-section-head"><div><div className="cf-eyebrow">AI CHAT WORKSPACE</div><h2>What do you want to create?</h2><p>Ask in your own words. CreatorFlow will turn your idea into a ready-to-use draft.</p></div><span className="cf-live">● Ready</span></div>
 <div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"0 0 18px"}}>{starterIdeas.map(idea=><button key={idea} className="cf-icon-btn" style={{fontSize:12}} onClick={()=>useIdea(idea)}>{idea}</button>)}</div>
 {messages.length>0&&<div style={{display:"grid",gap:12,marginBottom:18,maxHeight:430,overflowY:"auto"}}>{messages.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start"}}><div style={{maxWidth:"88%",padding:"13px 15px",borderRadius:16,background:m.role==="user"?"rgba(139,124,255,.18)":"rgba(255,255,255,.045)",border:"1px solid rgba(255,255,255,.08)",whiteSpace:"pre-wrap",lineHeight:1.6}}><div style={{fontSize:11,opacity:.6,marginBottom:5}}>{m.role==="user"?"You":"CreatorFlow AI"}</div>{m.text}</div></div>)}</div>}
 <div className="cf-chat-input" style={{display:"grid",gap:10}}><textarea className="cf-input cf-topic" style={{minHeight:125}} placeholder="Example: Write a 60-second YouTube script about how beginners can use AI to save time…" value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")generate()}}/><div style={{display:"flex",gap:8,justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"}}><span className="cf-muted" style={{fontSize:12}}>Ctrl/⌘ + Enter to generate • {activeTool.name}</span><button className="cf-btn cf-generate" onClick={generate} disabled={loading||!topic.trim()}>{loading?"Thinking…":"✦ Ask CreatorFlow"}</button></div></div>
 <details style={{marginTop:16}}><summary style={{cursor:"pointer",fontSize:13,opacity:.8}}>More controls (optional)</summary><div className="cf-form-grid" style={{marginTop:14}}><label>Language<select className="cf-input" value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x}>{x}</option>)}</select></label><label>Tone<select className="cf-input" value={tone} onChange={e=>setTone(e.target.value)}>{tones.map(x=><option key={x}>{x}</option>)}</select></label></div></details>
 {error&&<div role="alert" style={{marginTop:14,padding:"12px 14px",borderRadius:10,border:"1px solid rgba(255,120,120,.35)"}}>{error}</div>}
 {result&&<div className="cf-result" style={{marginTop:18}}><div className="cf-result-head"><div><div className="cf-eyebrow">LATEST OUTPUT</div><h2>Ready to use</h2></div><div className="cf-result-actions"><span>{action}</span><button className="cf-icon-btn" onClick={copyResult}>Copy</button><button className="cf-icon-btn" onClick={saveResult} disabled={action==="Saving..."}>Save</button></div></div><pre>{result}</pre></div>}
 </div>}</section></div></main>;
}
