"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import VisualCreator from "@/components/VisualCreator";
const tools=[{id:"youtube",icon:"▶",name:"YouTube Content",desc:"Titles, descriptions, tags & scripts"},{id:"shorts",icon:"⚡",name:"Shorts & Reels",desc:"Hooks and short-form scripts"},{id:"social",icon:"✦",name:"Social Posts",desc:"Facebook, Instagram & TikTok"},{id:"product",icon:"◇",name:"Product Copy",desc:"SEO-ready product descriptions"},{id:"visual",icon:"◈",name:"Visual Creator",desc:"Thumbnails, banners & social art"}];
const languages=["English","বাংলা","Hindi","Spanish","Portuguese","French","German","Arabic","Indonesian","Turkish"];
export default function Dashboard(){const[tool,setTool]=useState(tools[0].id),[language,setLanguage]=useState("English"),[topic,setTopic]=useState(""),[tone,setTone]=useState("Engaging"),[result,setResult]=useState(""),[loading,setLoading]=useState(false),[action,setAction]=useState(""),[credits,setCredits]=useState<number|null>(null);const router=useRouter();
 async function loadCredits(){try{const r=await fetch("/api/profile");const d=await r.json();if(typeof d.credits==="number")setCredits(d.credits)}catch{}}
 useEffect(()=>{loadCredits()},[]);
 async function generate(){if(!topic.trim())return;setLoading(true);setResult("");setAction("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tool,language,topic,tone})});const data=await r.json();setResult(data.output||data.error||"Something went wrong.");if(typeof data.credits==="number")setCredits(data.credits)}catch{setResult("Something went wrong. Please try again.")}finally{setLoading(false)}}
 async function copyResult(){if(!result)return;try{await navigator.clipboard?.writeText(result);setAction("Copied");setTimeout(()=>setAction(""),1600)}catch{setAction("Copy failed")}}
 async function saveResult(){if(!result)return;setAction("Saving...");try{const r=await fetch("/api/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:topic.slice(0,60),type:tool,content:result})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed");setAction("Saved");setTimeout(()=>setAction(""),1600)}catch(e){setAction(e instanceof Error?e.message:"Save failed");setTimeout(()=>setAction(""),2200)}}
 return <main className="cf-dashboard" style={{maxWidth:1380,margin:"0 auto",padding:"18px 20px 40px"}}><header className="cf-topbar"><button className="cf-brand" onClick={()=>router.push("/")}><span>Creator</span><strong>Flow</strong><em>AI</em></button><div className="cf-top-actions"><div className="cf-credit"><span>Credits</span><b>{credits??"—"}</b></div><button className="cf-icon-btn" onClick={()=>router.push("/history")}>History</button><button className="cf-icon-btn" onClick={()=>router.push("/settings")}>Settings</button><button className="cf-icon-btn" onClick={()=>router.push("/")}>Home</button></div></header>
 <section className="cf-welcome cf-glow"><div><div className="cf-eyebrow">CREATOR WORKSPACE</div><h1>Create faster. Publish smarter.</h1><p>Turn one idea into ready-to-use content, copy and visuals with CreatorFlow AI.</p></div><div className="cf-stat"><span>Available credits</span><strong>{credits??"—"}</strong><small>Use them to generate content</small></div></section>
 <div className="cf-workspace"><aside className="cf-sidebar cf-card"><div className="cf-sidebar-title">TOOLS</div>{tools.map(t=><button key={t.id} className={"cf-tool "+(tool===t.id?"active":"")} onClick={()=>{setTool(t.id);setAction("")}}><span className="cf-tool-icon">{t.icon}</span><span><b>{t.name}</b><small>{t.desc}</small></span><i>›</i></button>)}<div className="cf-sidebar-foot"><span>✦</span><div><b>CreatorFlow AI</b><small>Your all-in-one creator workspace</small></div></div></aside>
 <section className="cf-main">{tool==="visual"?<VisualCreator/>:<><div className="cf-card cf-generator"><div className="cf-section-head"><div><div className="cf-eyebrow">AI GENERATOR</div><h2>What are you creating?</h2><p>Describe your idea and let CreatorFlow build the first draft.</p></div><span className="cf-live">● Ready</span></div><div className="cf-form-grid"><label>Language<select className="cf-input" value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x}>{x}</option>)}</select></label><label>Tone<select className="cf-input" value={tone} onChange={e=>setTone(e.target.value)}><option>Engaging</option><option>Professional</option><option>Funny</option><option>Inspirational</option><option>Direct</option></select></label></div><label className="cf-topic-label">Your idea<textarea className="cf-input cf-topic" placeholder="Example: A YouTube video about 5 AI tools for small businesses..." value={topic} onChange={e=>setTopic(e.target.value)}/></label><div className="cf-generate-row"><span className="cf-muted">Be specific for better results.</span><button className="cf-btn cf-generate" onClick={generate} disabled={loading}>{loading?"Generating…":"✦ Generate content"}</button></div></div><div className="cf-card cf-result"><div className="cf-result-head"><div><div className="cf-eyebrow">OUTPUT</div><h2>Your result</h2></div><div className="cf-result-actions"><span>{action}</span><button className="cf-icon-btn" onClick={copyResult} disabled={!result}>Copy</button><button className="cf-icon-btn" onClick={saveResult} disabled={!result||action==="Saving..."}>Save</button></div></div><pre>{result||"Your generated content will appear here."}</pre></div></>}</section></div></main>;
}