"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import VisualCreator from "@/components/VisualCreator";

const tools=[{id:"youtube",icon:"▶",name:"YouTube Content",desc:"Titles, descriptions, tags & scripts"},{id:"shorts",icon:"⚡",name:"Shorts & Reels",desc:"Hooks and short-form scripts"},{id:"social",icon:"✦",name:"Social Posts",desc:"Facebook, Instagram & TikTok"},{id:"product",icon:"◇",name:"Product Copy",desc:"SEO-ready product descriptions"},{id:"visual",icon:"◈",name:"Visual Creator",desc:"Thumbnails, banners & social art"}];
const languages=["English","বাংলা","Hindi","Spanish","Portuguese","French","German","Arabic","Indonesian","Turkish"];
const tones=["Engaging","Professional","Funny","Inspirational","Direct"];
const starterIdeas=["5 AI tools that can save creators time","A 30-second motivational Reel for beginners","A Facebook post that introduces my new page","SEO product description for a wireless earbud"];

export default function Dashboard(){
 const[tool,setTool]=useState(tools[0].id),[language,setLanguage]=useState("English"),[topic,setTopic]=useState(""),[tone,setTone]=useState("Engaging"),[result,setResult]=useState(""),[loading,setLoading]=useState(false),[action,setAction]=useState(""),[credits,setCredits]=useState<number|null>(null),[error,setError]=useState("");
 const router=useRouter();
 const activeTool=useMemo(()=>tools.find(t=>t.id===tool)??tools[0],[tool]);
 async function loadCredits(){try{const r=await fetch("/api/profile",{cache:"no-store"});const d=await r.json();if(typeof d.credits==="number")setCredits(d.credits)}catch{}}
 useEffect(()=>{loadCredits()},[]);
 async function generate(){if(!topic.trim())return;setLoading(true);setResult("");setAction("");setError("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tool,language,topic:topic.trim(),tone})});const data=await r.json();if(!r.ok){setError(data.error||"We couldn't generate this yet. Please try again.");if(typeof data.credits==="number")setCredits(data.credits);return}setResult(data.output||"No content was returned. Please try again.");if(typeof data.credits==="number")setCredits(data.credits)}catch{setError("Connection problem. Please try again in a moment.")}finally{setLoading(false)}}
 async function copyResult(){if(!result)return;try{await navigator.clipboard?.writeText(result);setAction("Copied ✓");setTimeout(()=>setAction(""),1600)}catch{setAction("Copy failed")}}
 async function saveResult(){if(!result)return;setAction("Saving...");try{const r=await fetch("/api/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:topic.slice(0,60),type:tool,content:result})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed");setAction("Saved ✓");setTimeout(()=>setAction(""),1600)}catch(e){setAction(e instanceof Error?e.message:"Save failed");setTimeout(()=>setAction(""),2200)}}
 function chooseTool(id:string){setTool(id);setResult("");setError("");setAction("")}
 return <main className="cf-dashboard" style={{maxWidth:1380,margin:"0 auto",padding:"18px 20px 40px"}}><header className="cf-topbar"><button className="cf-brand" onClick={()=>router.push("/")}><span>Creator</span><strong>Flow</strong><em>AI</em></button><div className="cf-top-actions"><div className="cf-credit"><span>Credits</span><b>{credits??"—"}</b></div><button className="cf-icon-btn" onClick={()=>router.push("/history")}>History</button><button className="cf-icon-btn" onClick={()=>router.push("/settings")}>Settings</button><button className="cf-icon-btn" onClick={()=>router.push("/")}>Home</button></div></header>
 <section className="cf-welcome cf-glow"><div><div className="cf-eyebrow">CREATOR WORKSPACE</div><h1>Create faster. Publish smarter.</h1><p>Turn one idea into ready-to-use content, copy and visuals with CreatorFlow AI.</p><div style={{marginTop:14,fontSize:13,opacity:.82}}>Start with a tool below, or use a quick idea to get your first result.</div></div><div className="cf-stat"><span>Available credits</span><strong>{credits??"—"}</strong><small>Each successful generation uses 1 credit</small></div></section>
 <div className="cf-workspace"><aside className="cf-sidebar cf-card"><div className="cf-sidebar-title">TOOLS</div>{tools.map(t=><button key={t.id} className={"cf-tool "+(tool===t.id?"active":"")} onClick={()=>chooseTool(t.id)}><span className="cf-tool-icon">{t.icon}</span><span><b>{t.name}</b><small>{t.desc}</small></span><i>›</i></button>)}<div className="cf-sidebar-foot"><span>✦</span><div><b>CreatorFlow AI</b><small>Your all-in-one creator workspace</small></div></div></aside>
 <section className="cf-main">{tool==="visual"?<VisualCreator/>:<><div className="cf-card cf-generator"><div className="cf-section-head"><div><div className="cf-eyebrow">AI GENERATOR</div><h2>What are you creating?</h2><p>{activeTool.desc}. Describe your idea and CreatorFlow will build a first draft.</p></div><span className="cf-live">● Ready</span></div>
 <div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"0 0 16px"}}>{starterIdeas.map(idea=><button key={idea} className="cf-icon-btn" style={{fontSize:12}} onClick={()=>setTopic(idea)}>{idea}</button>)}</div>
 <div className="cf-form-grid"><label>Language<select className="cf-input" value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x}>{x}</option>)}</select></label><label>Tone<select className="cf-input" value={tone} onChange={e=>setTone(e.target.value)}>{tones.map(x=><option key={x}>{x}</option>)}</select></label></div>
 <label className="cf-topic-label">Your idea<textarea className="cf-input cf-topic" placeholder="Tell CreatorFlow what you want to create..." value={topic} onChange={e=>setTopic(e.target.value)}/></label><div className="cf-generate-row"><span className="cf-muted">Tip: specific goals, audience and platform usually produce better drafts.</span><button className="cf-btn cf-generate" onClick={generate} disabled={loading||!topic.trim()}>{loading?"Generating…":"✦ Generate content"}</button></div>{error&&<div role="alert" style={{marginTop:14,padding:"12px 14px",borderRadius:10,border:"1px solid rgba(255,120,120,.35)"}}>{error}</div>}</div>
 <div className="cf-card cf-result"><div className="cf-result-head"><div><div className="cf-eyebrow">OUTPUT</div><h2>Your result</h2></div><div className="cf-result-actions"><span>{action}</span><button className="cf-icon-btn" onClick={copyResult} disabled={!result}>Copy</button><button className="cf-icon-btn" onClick={saveResult} disabled={!result||action==="Saving..."}>Save</button></div></div><pre>{result||"Your generated content will appear here. Choose a tool, try a quick idea, and generate your first result."}</pre></div></>}</section></div></main>;
}
