"use client";
import { useMemo, useState } from "react";

type Props={tool:string};
const num=(v:string)=>Math.max(0,Number(v)||0);
export default function GrowthTools({tool}:Props){
 const [x,setX]=useState<Record<string,string>>({duration:"5",retention:"45",views:"10000",targetHours:"4000",currentSubs:"100",targetSubs:"1000",growth:"10",avgWatch:"30",currentFollowers:"100",targetFollowers:"1000",dailyFollowers:"10"});
 const set=(k:string,v:string)=>setX(a=>({...a,[k]:v})); const g=(k:string)=>x[k]??"";
 const Field=({label,id,suffix}:{label:string,id:string,suffix?:string})=><label style={{display:"grid",gap:6,fontSize:13}}>{label}<div style={{display:"flex",alignItems:"center",gap:6}}><input className="cf-input" inputMode="decimal" value={g(id)} onChange={e=>set(id,e.target.value)}/>{suffix&&<span className="cf-muted">{suffix}</span>}</div></label>;
 const watch=useMemo(()=>num(g("views"))*num(g("duration"))*num(g("retention"))/6000,[x]);
 const days=useMemo(()=>num(g("growth"))?(num(g("targetSubs"))-num(g("currentSubs")))/num(g("growth")):0,[x]);
 const fdays=useMemo(()=>num(g("dailyFollowers"))?(num(g("targetFollowers"))-num(g("currentFollowers")))/num(g("dailyFollowers")):0,[x]);
 const ret=useMemo(()=>num(g("duration"))?Math.min(100,num(g("avgWatch"))/num(g("duration"))*100):0,[x]);
 if(tool.toLowerCase().includes("watch")) return <section className="cf-card" style={{padding:18}}><div className="cf-eyebrow">ANALYTICS PLANNER</div><h2>YouTube Watch-Time Planner</h2><p className="cf-muted">Estimate watch hours from your own assumptions. No live metrics are fabricated.</p><div className="cf-form-grid"><Field label="Video duration" id="duration" suffix="min"/><Field label="Average retention" id="retention" suffix="%"/><Field label="Expected views" id="views"/><Field label="Target watch hours" id="targetHours" suffix="hours"/></div><div style={{marginTop:18,fontSize:18,fontWeight:700}}>{watch.toFixed(1)} estimated watch hours</div><small className="cf-muted">{num(g("targetHours"))?(watch/num(g("targetHours"))*100).toFixed(1):0}% of target</small></section>;
 if(tool.toLowerCase().includes("subscriber")) return <section className="cf-card" style={{padding:18}}><div className="cf-eyebrow">GROWTH PLANNER</div><h2>YouTube Subscriber Growth Planner</h2><p className="cf-muted">Transparent scenario planning based on your daily growth assumption.</p><div className="cf-form-grid"><Field label="Current subscribers" id="currentSubs"/><Field label="Target subscribers" id="targetSubs"/><Field label="Expected new subscribers / day" id="growth"/></div><div style={{marginTop:18,fontSize:18,fontWeight:700}}>{days>0?`${Math.ceil(days)} days estimated`:"Enter a positive daily growth assumption"}</div></section>;
 if(tool.toLowerCase().includes("follower")) return <section className="cf-card" style={{padding:18}}><div className="cf-eyebrow">GROWTH CALCULATOR</div><h2>Follower Growth Calculator</h2><div className="cf-form-grid"><Field label="Current followers" id="currentFollowers"/><Field label="Target followers" id="targetFollowers"/><Field label="Expected growth / day" id="dailyFollowers"/></div><div style={{marginTop:18,fontSize:18,fontWeight:700}}>{fdays>0?`${Math.ceil(fdays)} days estimated`:"Enter a positive daily growth assumption"}</div></section>;
 if(tool.toLowerCase().includes("retention")||tool.toLowerCase().includes("completion")||tool.toLowerCase().includes("analyzer")) return <section className="cf-card" style={{padding:18}}><div className="cf-eyebrow">RETENTION ANALYZER</div><h2>Retention & Completion Planner</h2><p className="cf-muted">Use your video length and average watch duration to understand retention.</p><div className="cf-form-grid"><Field label="Video duration" id="duration" suffix="sec"/><Field label="Average watch duration" id="avgWatch" suffix="sec"/></div><div style={{marginTop:18,fontSize:18,fontWeight:700}}>{ret.toFixed(1)}% estimated average retention</div><p className="cf-muted">{ret>=70?"Strong signal—protect the opening and pacing.":ret>=40?"Moderate signal—test a stronger hook and tighter pacing.":"Review the opening, pacing and payoff."}</p></section>;
 return null;
}