"use client";
import {useEffect,useState} from "react";

type Connection={id:string;platform:string;status:string;external_account_id?:string|null;external_account_name?:string|null;scopes:string[];created_at:string;updated_at:string};
const names:Record<string,string>={youtube:"YouTube",instagram:"Instagram",tiktok:"TikTok",facebook:"Facebook",linkedin:"LinkedIn",shopify:"Shopify",whatsapp:"WhatsApp Business",wordpress:"WordPress","google-business":"Google Business Profile"};
const connectable=["youtube","instagram","tiktok","facebook","linkedin","shopify","whatsapp","wordpress","google-business"];
export default function PlatformConnections(){const [items,setItems]=useState<Connection[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [msg,setMsg]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/integrations",{cache:"no-store"});if(!r.ok)throw new Error("Unable to load connections");const d=await r.json();setItems(d.connections||[])}catch(e){setMsg(e instanceof Error?e.message:"Unable to load connections")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function disconnect(id:string){setBusy(id);setMsg("");try{const r=await fetch("/api/integrations",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(!r.ok)throw new Error("Could not disconnect account");await load()}catch(e){setMsg(e instanceof Error?e.message:"Could not disconnect account")}finally{setBusy("")}}
 return <section className="cf-card" style={{padding:22}}><div className="cf-eyebrow">ACCOUNT CONNECTIONS</div><h2 style={{margin:"6px 0"}}>Platform connections</h2><p className="cf-muted">Connect only through official OAuth/API flows. CreatorFlow never marks an account connected without a real connection.</p>{loading?<p className="cf-muted">Checking connections…</p>:<div style={{display:"grid",gap:10,marginTop:14}}>{connectable.map(p=>{const c=items.find(x=>x.platform===p&&x.status==="connected");return <div key={p} className="cf-card" style={{padding:14,display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><strong>{names[p]||p}</strong><div className="cf-muted" style={{fontSize:12,marginTop:3}}>{c?`Connected${c.external_account_name?` · ${c.external_account_name}`:""}`:"Not connected"}</div></div>{c?<button className="cf-icon-btn" disabled={busy===c.id} onClick={()=>disconnect(c.id)}>{busy===c.id?"Removing…":"Disconnect"}</button>:<span className="cf-muted" style={{fontSize:12}}>Official setup required</span>}</div>})}</div>}{msg&&<div className="cf-muted" style={{marginTop:12}}>{msg}</div>}</section>}
