"use client";
import { useState } from "react";

const types = [["thumbnail","🎯","YouTube Thumbnail","16:9"],["banner","📺","Channel Banner","16:9"],["social","📱","Social Post","1:1"],["cover","⚡","TikTok Cover","1:1"]];
const styles = ["Cinematic","Modern","Minimal","Bold & Energetic","Luxury","Dark & Dramatic","Bright & Clean"];

export default function VisualCreator(){
 const [type,setType]=useState("thumbnail"),[style,setStyle]=useState("Cinematic"),[prompt,setPrompt]=useState(""),[text,setText]=useState(""),[loading,setLoading]=useState(false),[image,setImage]=useState<string|null>(null),[demo,setDemo]=useState("");
 const selected=types.find(x=>x[0]===type)!;
 async function generate(){if(!prompt.trim())return;setLoading(true);setImage(null);setDemo("");try{const r=await fetch("/api/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:selected[2],style,prompt,text,aspectRatio:selected[3]})});const d=await r.json();if(d.imageUrl)setImage(d.imageUrl);else setDemo(d.prompt||d.error||"Something went wrong.");}catch{setDemo("Could not generate the visual. Please try again.");}finally{setLoading(false)}}
 return <div className="cf-card cf-visual">
  <div className="cf-visual-head"><div><div className="cf-eyebrow">VISUAL CREATOR</div><h2>Bring your idea to life.</h2><p>Create thumbnails, banners and social visuals from one simple prompt.</p></div><span className="cf-live">● AI Ready</span></div>
  <div className="cf-visual-types">{types.map(x=><button key={x[0]} className={type===x[0]?"active":""} onClick={()=>setType(x[0])}><span>{x[1]}</span><b>{x[2]}</b><small>{x[3]}</small></button>)}</div>
  <div className="cf-visual-grid">
   <div className="cf-visual-form">
    <div className="cf-form-grid"><label>Visual style<select className="cf-input" value={style} onChange={e=>setStyle(e.target.value)}>{styles.map(x=><option key={x}>{x}</option>)}</select></label><label>Aspect ratio<input className="cf-input" value={selected[3]} readOnly/></label></div>
    <label className="cf-topic-label">Text on image <span>(optional)</span><input className="cf-input" placeholder="Example: NEVER GIVE UP" value={text} onChange={e=>setText(e.target.value)}/></label>
    <label className="cf-topic-label">Describe your visual <span>(be specific)</span><textarea className="cf-input cf-topic" placeholder="Example: A determined creator in a futuristic city at night, cinematic lighting, dramatic atmosphere..." value={prompt} onChange={e=>setPrompt(e.target.value)}/></label>
    <div className="cf-generate-row"><span className="cf-muted">Tip: describe subject, mood, lighting and background.</span><button className="cf-btn cf-generate" onClick={generate} disabled={loading}>{loading?"Creating…":"✦ Generate visual"}</button></div>
   </div>
   <div className="cf-visual-preview">{image?<><img src={image} alt="Generated creator visual"/><div className="cf-preview-actions"><a className="cf-btn" href={image} target="_blank" rel="noreferrer">Open image</a><button className="cf-icon-btn" onClick={()=>setImage(null)}>Clear</button></div></>:demo?<pre>{demo}</pre>:<div className="cf-empty"><div>◈</div><b>Your visual will appear here</b><span>Choose a format, describe your idea and generate.</span></div>}</div>
  </div>
  <style jsx>{` .cf-visual{padding:26px}.cf-visual-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.cf-visual-head h2{font-size:24px;margin:5px 0}.cf-visual-head p{color:var(--muted);font-size:13px;margin:0}.cf-visual-types{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:24px 0}.cf-visual-types button{display:grid;grid-template-columns:34px 1fr;grid-template-rows:1fr 1fr;text-align:left;gap:0 9px;padding:13px;border:1px solid var(--border);border-radius:15px;background:rgba(255,255,255,.035);color:white;cursor:pointer}.cf-visual-types button.active{border-color:rgba(124,92,255,.55);background:rgba(124,92,255,.13)}.cf-visual-types span{grid-row:1/3;width:34px;height:34px;display:grid;place-items:center;background:rgba(255,255,255,.07);border-radius:10px}.cf-visual-types b{font-size:12px}.cf-visual-types small{font-size:10px;color:var(--muted)}.cf-visual-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.85fr);gap:18px}.cf-visual-form{min-width:0}.cf-topic-label span{font-weight:400;color:#718096}.cf-topic{min-height:150px}.cf-visual-preview{min-height:360px;border:1px dashed rgba(255,255,255,.14);border-radius:18px;background:rgba(0,0,0,.16);display:flex;align-items:center;justify-content:center;overflow:hidden;position:relative}.cf-visual-preview img{width:100%;height:auto;display:block}.cf-empty{text-align:center;padding:30px;color:var(--muted)}.cf-empty div{font-size:38px;color:#9b8cff;margin-bottom:12px}.cf-empty b,.cf-empty span{display:block}.cf-empty b{color:white;margin-bottom:5px}.cf-empty span{font-size:11px;max-width:220px}.cf-visual-preview pre{white-space:pre-wrap;padding:20px;line-height:1.6;color:var(--muted);overflow:auto}.cf-preview-actions{position:absolute;bottom:12px;right:12px;display:flex;gap:8px}.cf-visual :global(.cf-form-grid){margin:0 0 14px}.cf-visual :global(.cf-generate-row){margin-top:14px}.cf-visual :global(.cf-generate){width:auto}.cf-visual :global(.cf-input){margin-top:7px}.cf-visual :global(.cf-topic-label){display:block;font-size:12px;color:var(--muted);font-weight:700;margin-top:14px}.cf-visual :global(.cf-topic){resize:vertical}.cf-visual :global(.cf-icon-btn){min-height:44px}@media(max-width:900px){.cf-visual-grid{grid-template-columns:1fr}.cf-visual-preview{min-height:300px}.cf-visual-types{grid-template-columns:1fr 1fr}}@media(max-width:560px){.cf-visual{padding:18px}.cf-visual-head{flex-direction:column}.cf-visual-types{grid-template-columns:1fr}.cf-visual :global(.cf-generate-row){align-items:stretch;flex-direction:column}.cf-visual :global(.cf-generate){width:100%}.cf-preview-actions{left:12px;right:12px}.cf-preview-actions .cf-btn,.cf-preview-actions .cf-icon-btn{flex:1}}`}</style>
 </div>
}
