"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Item={id:string;title:string;image_url:string;image_type:string;prompt:string|null;created_at:string};

export default function ImagesPage(){
 const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [action,setAction]=useState(""); const router=useRouter();
 useEffect(()=>{fetch("/api/images",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load visuals");setItems(d.items||[])}).catch(e=>setError(e instanceof Error?e.message:"Could not load visuals")).finally(()=>setLoading(false))},[]);
 async function remove(id:string){if(!confirm("Delete this saved visual?"))return;setAction("Deleting...");try{const r=await fetch("/api/delete",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,table:"saved_images"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not delete visual");setItems(x=>x.filter(i=>i.id!==id));setAction("Deleted ✓")}catch(e){setAction(e instanceof Error?e.message:"Could not delete visual")}finally{setTimeout(()=>setAction(""),1800)}}
 return <main style={{maxWidth:1200,margin:"0 auto",padding:"24px 16px 60px"}}>
  <header style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:16,marginBottom:24,flexWrap:"wrap"}}><div><div style={{fontWeight:900,fontSize:22}}>Creator<span style={{color:"#8b7cff"}}>Flow</span> AI</div><div className="cf-muted" style={{marginTop:6,fontSize:13}}>Your saved visual workspace</div><h1 style={{margin:"10px 0 0",fontSize:"clamp(28px,5vw,38px)",letterSpacing:-1}}>Saved Visuals</h1></div><div style={{display:"flex",gap:9,alignItems:"center",flexWrap:"wrap"}}>{action&&<span className="cf-muted" style={{fontSize:13}}>{action}</span>}<button className="cf-btn" onClick={()=>router.push("/dashboard")}>← Dashboard</button></div></header>
  {loading?<div className="cf-card" style={{padding:28,textAlign:"center"}}><b>Loading saved visuals…</b></div>:error?<div className="cf-card" style={{padding:28,textAlign:"center"}}><h2>Couldn’t load visuals</h2><p className="cf-muted">{error}</p><button className="cf-btn" onClick={()=>location.reload()}>Try again</button></div>:items.length===0?<div className="cf-card" style={{padding:"42px 24px",textAlign:"center"}}><div style={{fontSize:34}}>◈</div><h2>No saved visuals yet</h2><p className="cf-muted">Generate a thumbnail, banner or social visual and save it here.</p><button className="cf-btn" onClick={()=>router.push("/dashboard")}>Create a visual →</button></div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:16}}>{items.map(i=><article className="cf-card" key={i.id} style={{overflow:"hidden"}}><img src={i.image_url} alt={i.title||"Saved visual"} style={{display:"block",width:"100%",aspectRatio:"16/10",objectFit:"cover"}}/><div style={{padding:15}}><b style={{display:"block",overflowWrap:"anywhere"}}>{i.title||"Untitled visual"}</b><div className="cf-muted" style={{fontSize:11,marginTop:5}}>{i.image_type} · {new Date(i.created_at).toLocaleString()}</div>{i.prompt&&<p className="cf-muted" style={{fontSize:12,lineHeight:1.5,margin:"9px 0",display:"-webkit-box",WebkitLineClamp:3,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{i.prompt}</p>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}><a className="cf-icon-btn" href={i.image_url} target="_blank" rel="noreferrer">Open</a><button className="cf-icon-btn" onClick={()=>remove(i.id)}>Delete</button></div></div></article>)}</div>}
 </main>
}
