"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import PlatformConnections from "@/components/PlatformConnections";
type Profile={credits:number;plan:string;display_name?:string|null};
type Subscription={provider:string;plan:string;status:string;current_period_start?:string|null;current_period_end?:string|null};
type Transaction={id:string;provider:string;product_type:string;plan:string|null;credits:number;amount_minor:number;currency:string;status:string;created_at:string};
type ServiceStatus={ai:{text:string;image:string};billing:{payments:string}};
function Status({value}:{value:string}){const ready=value==="connected";return <span className="cf-live" style={{display:"inline-flex",marginTop:8}}>{ready?"● Connected":"● Not connected"}</span>}
function money(t:Transaction){return t.currency.toUpperCase()+" "+(t.amount_minor/100).toFixed(2);}
export default function Settings(){
  const router=useRouter(); const [profile,setProfile]=useState<Profile>({credits:0,plan:"free"}); const [subscription,setSubscription]=useState<Subscription|null>(null); const [transactions,setTransactions]=useState<Transaction[]>([]); const [services,setServices]=useState<ServiceStatus|null>(null); const [email,setEmail]=useState(""); const [name,setName]=useState(""); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
  useEffect(()=>{const supabase=createClient();supabase.auth.getUser().then(({data})=>{if(!data.user){router.replace("/login?next=/settings");return}setEmail(data.user.email||"");setName((data.user.user_metadata?.display_name as string)||"")});fetch("/api/profile",{cache:"no-store"}).then(r=>r.json()).then(d=>setProfile({credits:d.credits??0,plan:d.plan??"free",display_name:d.display_name})).catch(()=>{});fetch("/api/billing/status",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setSubscription(d?.subscription??null)).catch(()=>{});fetch("/api/billing/transactions",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setTransactions(d?.transactions??[])).catch(()=>{});fetch("/api/system/status",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setServices(d)).catch(()=>{})},[router]);
  async function save(){setSaving(true);setMsg("");try{const r=await fetch("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({display_name:name})});if(!r.ok)throw new Error("Could not save settings");setMsg("Settings saved")}catch(e){setMsg(e instanceof Error?e.message:"Could not save settings")}finally{setSaving(false)}}
  async function signOut(){const supabase=createClient();await supabase.auth.signOut();router.replace("/login")}
  return <main style={{maxWidth:900,margin:"0 auto",padding:"24px 16px 60px"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:16,flexWrap:"wrap",marginBottom:24}}><div><div style={{fontWeight:900,fontSize:22}}>Create<span style={{color:"#8b7cff"}}>Soul</span> AI</div><div className="cf-muted" style={{marginTop:6,fontSize:13}}>Workspace preferences</div><h1 style={{margin:"10px 0 0",fontSize:"clamp(28px,5vw,38px)"}}>Settings</h1></div><button className="cf-btn" onClick={()=>router.push("/dashboard")}>← Dashboard</button></header><div style={{display:"grid",gap:16}}>
<section className="cf-card cf-glow" style={{padding:22}}><h2>Account</h2><p className="cf-muted">Manage your CreateSoul AI profile.</p><label className="cf-muted">Display name<input className="cf-input" style={{marginTop:7}} value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label className="cf-muted" style={{display:"block",marginTop:14}}>Email<input className="cf-input" style={{marginTop:7,opacity:.7}} value={email} readOnly/></label><button className="cf-btn" style={{marginTop:14}} onClick={save} disabled={saving}>{saving?"Saving…":"Save changes"}</button>{msg&&<span className="cf-muted" style={{display:"block",marginTop:10}}>{msg}</span>}</section>
<section className="cf-card" style={{padding:22}}><h2>AI services</h2><p className="cf-muted">Live AI usage is separate from your ChatGPT plan. CreateSoul AI only uses a usage-based API when it is configured.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginTop:14}}><div><div className="cf-muted">Text generation</div>{services?<Status value={services.ai.text}/>:<span className="cf-muted">Checking…</span>}</div><div><div className="cf-muted">Image generation</div>{services?<Status value={services.ai.image}/>:<span className="cf-muted">Checking…</span>}</div></div>{services?.ai.text!=="connected"&&<p className="cf-muted" style={{fontSize:12,marginTop:14}}>Paid AI usage is not activated from this page.</p>}</section>
<PlatformConnections/>
<section className="cf-card" style={{padding:22}}><h2>Plan & credits</h2><p className="cf-muted">Current usage available to your account.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><div><div className="cf-muted">Current plan</div><div style={{fontSize:22,fontWeight:900,textTransform:"capitalize"}}>{profile.plan}</div></div><div><div className="cf-muted">Credits remaining</div><div style={{fontSize:22,fontWeight:900}}>{profile.credits}</div></div></div><p className="cf-muted" style={{fontSize:12,marginTop:12}}>Credits are reserved only when a live AI generation is available; unavailable AI services do not charge your credits.</p></section>
<section className="cf-card" style={{padding:22}}><h2>Billing</h2><p className="cf-muted">{subscription?"Current subscription: "+subscription.plan+" · "+subscription.status:"No paid subscription is active."}</p><button className="cf-btn" onClick={()=>router.push("/pricing")}>{subscription?"View plans":"View upgrade plans"}</button><div className="cf-muted" style={{marginTop:10,fontSize:12}}>Payments are not enabled yet. No charge will be made from this page.</div><div style={{marginTop:20}}><h3 style={{marginBottom:8}}>Transaction history</h3>{transactions.length===0?<div className="cf-muted" style={{fontSize:13}}>No billing transactions yet.</div>:<div style={{display:"grid",gap:8}}>{transactions.map(t=><div key={t.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:10,padding:"10px 12px",border:"1px solid rgba(255,255,255,.08)",borderRadius:10}}><div><strong>{t.product_type==="subscription"?"Subscription · "+(t.plan||"plan"):"Credit purchase"}</strong><div className="cf-muted" style={{fontSize:12}}>{t.provider+" · "+new Date(t.created_at).toLocaleString()}</div></div><div style={{textAlign:"right"}}><strong>{money(t)}</strong><div className="cf-muted" style={{fontSize:12}}>{t.status}</div></div></div>)}</div>}</div></section>
<section className="cf-card" style={{padding:22}}><h2>Workspace</h2><p className="cf-muted">Jump between your creation workspace, saved library and history.</p><div style={{display:"flex",gap:9,flexWrap:"wrap",marginTop:14}}><button className="cf-btn" onClick={()=>router.push("/history")}>History</button><button className="cf-btn" onClick={()=>router.push("/saved")}>Saved</button><button className="cf-btn" onClick={()=>router.push("/platforms")}>Platform Hub</button><button className="cf-btn" onClick={()=>router.push("/dashboard")}>Create Content</button></div></section>
<section className="cf-card" style={{padding:22}}><h2>Sign out</h2><p className="cf-muted">End your current CreateSoul AI session on this device.</p><button className="cf-btn" onClick={signOut}>Sign out</button></section></div></main>
}